# Generated by Django 5.2.5 on 2026-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_staff_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in original currency', max_digits=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Debt amount in original currency', max_digits=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount in original currency', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleetb',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in ETB', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleetb',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Debt amount in ETB', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleetb',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in ETB', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemetb',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity bought', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemetb',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price in ETB', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemetb',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price in ETB', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemsos',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity bought', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemsos',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price in SOS', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemsos',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price in SOS', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemusd',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity bought', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemusd',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='Total price in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitemusd',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit price in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='salesos',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in SOS', max_digits=20),
        ),
        migrations.AlterField(
            model_name='salesos',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Debt amount in SOS', max_digits=20),
        ),
        migrations.AlterField(
            model_name='salesos',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in SOS', max_digits=20),
        ),
    ]
