# Generated by Django 5.2.5 on 2026-02-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_sale_amount_paid_alter_sale_debt_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtpayment',
            name='pno',
            field=models.CharField(max_length=50, null=True, verbose_name='Receipt Number (PNO)'),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Payment amount in base currency (SOS)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleusd',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleusd',
            name='debt_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Debt amount in USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleusd',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount in USD', max_digits=20),
        ),
    ]
