# Generated by Django 5.2.5 on 2026-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_debtpayment_pno_alter_debtpayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer PNO'),
        ),
    ]
