# Generated by Django 5.2.5 on 2026-02-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_customer_pno'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleetb',
            name='pno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sale PNO'),
        ),
        migrations.AddField(
            model_name='salesos',
            name='pno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sale PNO'),
        ),
        migrations.AddField(
            model_name='saleusd',
            name='pno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sale PNO'),
        ),
    ]
